# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Routine-SQLBuilder
version:      v0.21.1
version_from: lib/SQL/Routine/SQLBuilder.pm
installdirs:  site
requires:
    Locale::KeyedText:             1.6.0
    only:                          0
    SQL::Routine:                  0.70.0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
