# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Routine-SQLBuilder
version:      0.17
version_from: lib/SQL/Routine/SQLBuilder.pm
installdirs:  site
requires:
    Locale::KeyedText:             1.03
    SQL::Routine:                  0.58
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
